[build]
  publish = "dist"

[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "no-cache"
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "no-cache"
